### ISSUE TITLE
Improve AOE Radius math

### ISSUE THREAD

**Issue by ThePhilderbeast** [ThePhilderbeast/prisonPicks#11]
The AOE radius code currently isn't very intuitive and makes getting desirable results difficult. This should be fixed so AOE radius customization can be added in the future.

**Comment by drekryan** [comment]
I dont know how much it absolutely needs to change. Its not broken at the moment so not sure changing it would be of benefit

**Comment by ThePhilderbeast** [comment]
finally cleaned this up so the loops are not cycling through extra blocks.
