### ISSUE TITLE
Remove Inventory Full Notification

### ISSUE THREAD

**Issue by drekryan** [ThePhilderbeast/prisonPicks#17]
The Inventory Full Notification should be moved to AutoPickup in full and the /fullnotify command will be removed entirely. The reasoning for this is to not duplicate the code across both plugins for both AutoBlock and non-AutoBlock as it seems messy. Also creating an API on the prisonPicks side for AutoBlock to use could cause performance problems due to the rate it would have to check to see if the settings have been changed. From a code standpoint the prisonPicks plugin should not care whether inventory space is available or not. It should always try adding the item regardless and let AutoPickup handle what to do with it. Whether that may be deleting excess items or dropping them to the ground.

**Comment by ThePhilderbeast** [comment]
AutoPickupPlugin.autoBlock.contains(player.getName()) tells us if autoblock is on

**Comment by drekryan** [comment]
Only issue is can we capture what items auto block turns into blocks? How can we tell if there are stacks that aren't max stack size yet? This is hard because we don't really have access to what autoblock is doing. Not sure how possible this will be yet because of that

**Comment by ThePhilderbeast** [comment]
https://github.com/MnMaxon/AutoPickup is the repo for it so we can take a look in there for what it does.
