### ISSUE TITLE
Make AutoPickup a soft dependency

### ISSUE THREAD

**Issue by drekryan** [ThePhilderbeast/prisonPicks#26]
AutoPickup should be a soft dependency. Where we use it if the plugin is available but do our own handling if the AutoPickup plugin cannot be found.

Currently we will crash without the AutoPickup plugin. This plugin SHOULD be able to work without AutoPickup available.

**Comment by ThePhilderbeast** [comment]
this isnt a bug. im also adding wordlguard to this to be treated as a soft dependency.

i have started to work on this already as i need it for unit testing

**Comment by drekryan** [comment]
What do you mean this isn't a bug? Crashing is a bug

**Comment by ThePhilderbeast** [comment]
the code change is an enhancement not a bug fix. the missing dependency crash is seperate. i need to open an issue on autopickup as we should be able te remove the calls to it alltogether
