### ISSUE TITLE
server crashed is autopickup is not installed

### ISSUE THREAD

**Issue by ThePhilderbeast** [ThePhilderbeast/prisonPicks#27]
auto pickup needs to be added as a hard dependency

**Comment by ThePhilderbeast** [comment]
this is not a bug, this is due to autopickup being a hard dependency and is the correct behaviour

**Comment by drekryan** [comment]
AutoPickup should NOT be a hard dependency. Are you crazy?!? The pickaxe should work without AutoPickup. I don't see why they can't

**Comment by ThePhilderbeast** [comment]
there is an issue to change that, but its not a bug so this one gets closed.
