### ISSUE TITLE
Disappearing picks on repair

### ISSUE THREAD

**Issue by drekryan** [ThePhilderbeast/prisonPicks#8]
This bug has been reported by some people but I havent been able to reproduce it. Ill have to take a further look into why this would happen

**Comment by drekryan** [comment]
Unable to reproduce.. Closing until I get more information

**Comment by drekryan** [comment]
Reopening on request of Sketch

**Comment by ThePhilderbeast** [comment]
have we got any more information on this?

without some confirmation of this there isn't much point re-opening this.

**Comment by drekryan** [comment]
It happened to someone Sketch trusts. While I agree with you it doesn't mean it's not an issue.

**Comment by ThePhilderbeast** [comment]
have we had any confirmed reports of this? if not im going to close this as it has not been reproduced

**Comment by drekryan** [comment]
I really don't see why it cant be left open as something to investigate and not ignore but sure closing until we have more information I guess. Since this issue seems to bother you quite a bit.

**Comment by ThePhilderbeast** [comment]
1. we have not had a confirmed reproduceable report of this despite looking st it for  almost 2 weeks now.
2. the inital report was several build ago. so if it was an issue, chances are we might have fixed it with something else.
3. if we cant confirm the bug jn the current version we should vlose it and spen out time on confirmed bugs.
